### ISSUE TITLE
related valid emails

### ISSUE THREAD

**Issue by shyambaseapp** [stymiee/email-validator#2]
If we provide valid email  in $testEmailAddresses at the zero index in  array like this: 

$testEmailAddresses = [
    'test@johnconde.net',
    'test@gmail.com',
    'test@hotmail.com',
    'test@outlook.com',
    'test@yahoo.com',
    'test@domain.com',
    'test@mxfuel.com',
    'test@example.com',
    'test@example2.com',
    'test@nobugmail.com',
    'test@cellurl.com',
    'test@10minutemail.com',
];
It run perfect. 

output :  
Email is valid
Domain is used by free email providers
Domain is used by free email providers
Domain is used by free email providers
Domain is used by free email providers
Domain is banned
Domain is used by disposable email providers
Domain is used by disposable email providers
Domain is used by free email providers
Domain is used by disposable email providers
Domain is used by disposable email providers
Domain is used by disposable email providers

But if want to put valid emails in between two other types of emails 
(change the position of valid emails in array  $testEmailAddresses).
Then it give wrong output.
$testEmailAddresses = [
    'test@domain.com',
    'test@johnconde.net',
    'test@gmail.com',
    'test@hotmail.com',
    'test@outlook.com',
    'test@yahoo.com',
    'test@domain.com',
    'test@mxfuel.com',
    'test@example.com',
    'test@example2.com',
    'test@nobugmail.com',
    'test@cellurl.com',
    'test@10minutemail.com',
];

output:  Domain is banned
Domain is banned
Domain is used by free email providers
Domain is used by free email providers
Domain is used by free email providers
Domain is used by free email providers
Domain is banned
Domain is used by disposable email providers
Domain is used by disposable email providers
Domain is used by free email providers
Domain is used by disposable email providers
Domain is used by disposable email providers
Domain is used by disposable email providers

**Comment by stymiee** [comment]
Sorry for the delay is addressing this. Thank you for reporting this. I have fixed this issue and pushed out a new release (1.0.2) to address it.
