### ISSUE TITLE
Add validation for Gmail domain alias like Googlemail.com

### ISSUE THREAD

**Issue by jasomdotnet** [stymiee/email-validator#6]
Hi @stymiee,

`googlemail.com` is domain alias for `gmail.com`. So I suggest to add feature which considers following email addresses as one:

```
example.com@gmail.com
example.com@googlemail.com
e.x.a.m.p.l.e.c.o.m@gmail.com
example.com+string@gmail.com
```
See [this](https://gmail.googleblog.com/2008/03/2-hidden-ways-to-get-more-from-your.html).

**Comment by stymiee** [comment]
Good call out. I am going to add `googlemail.com` as a recognized Gmail domain and remove periods when analyzing Gmail addressing.

**Comment by stymiee** [comment]
I've added support for `googlemail.com` to be recognized as a Gmail domain name. Also, dotes in the username will be removed when sanitizing Gmail addresses so all of the examples you made above should be considered equal. I have another issue to address but this will be in the upcoming 1.1.4 release.
